### ISSUE TITLE
Error Object has no method `ui`

### ISSUE THREAD

**Issue by marr** [webpack/mocha-loader#17]
```
ERROR in ./~/mocha!./test/index.js
Module build failed: TypeError: Object #<Object> has no method 'ui'
    at Object.Mocha (/Users/dmarr/src/webpack-with-common-libs/node_modules/mocha/lib/mocha.js:83:8)
 @ multi main
```
When I try to run a test via w-d-s: `webpack-dev-server "mocha\!./test/index.js" --inline --hot --https --output-file m`

I then think that the url I'd browse to would be `https://localhost:8080/m` as I believe thats how the docs on webpack say to use this loader in their docs: http://webpack.github.io/docs/testing.html#webpack-dev-server

**Comment by marr** [comment]
test/index.js: https://gist.github.com/6050e5080d50063be341

**Comment by wbuchwalter** [comment]
Did you forget to install mocha-loader?
````
npm install mocha-loader --save
```

**Comment by rupurt** [comment]
@marr @wbuchwalter do you have any updates on this? I'm also seeing this exact error.

**Comment by rupurt** [comment]
@marr @wbuchwalter `npm install mocha-loader --save-dev` fixed my issue. Cheers

**Comment by hackhat** [comment]
The error could have a better error message...

**Comment by tricoder42** [comment]
@hackhat I definitely agree. 

However, from the stacktrace you can see the error is raised in `mocha` lib itself and reading this thread it seems that it's caused by missing `mocha-loader`… So it's either `mocha` issue or `webpack` itself, because `mocha-loader` isn't installed at all.
