### ISSUE TITLE
recursive test loading?

### ISSUE THREAD

**Issue by UnicodeSnowman** [webpack/mocha-loader#20]
Hi there,

I've gotten this working with a single entry test file, but is there some way to load a directory of tests, a la mocha's `--recursive` flag? I was reading through the code but didn't come across anything. 

That being said, perhaps this is the wrong approach, so any other suggestions are welcome. Thanks!

**Comment by dmwyatt** [comment]
I'm a confused by this as well.  AFAICT, mocha tests are very commonly spread amongst multiple files and subdirs.  The 3 or 4 examples I checked from mocha's [list of examples](https://mochajs.org/#examples) just have a bunch of .js files without a single entry point.

So...mocha doesn't have a representative list of examples, or mocha-loader doesn't support the most common way of structuring tests, or....?

**Comment by inversion** [comment]
You can work around it with a bit of bash scripting:

`find tests -name '*.js' | xargs -n1 printf 'mocha!./%s '`

In context:

`webpack-dev-server web.js $(find tests -name '*.js' | xargs -n1 printf 'mocha!./%s ')`

**Comment by tricoder42** [comment]
Example added to the README. If you have more questions, feel free to reopen this issue
