### ISSUE TITLE
getting started.

### ISSUE THREAD

**Issue by tomazzaman** [webpack/mocha-loader#21]
Hey, I've been rolling my head around this issue for a couple of days now and since Google didn't provide anything, I decided to ask here.

I'm currently testing my modules with gulp + mocha (no webpack), and it looks something like this:

```javascript
gulp.task( 'watch', function() {
  watch( [ './test/*.spec.js' ], function() {
    gulp.start( 'test' );
  });
});

gulp.task( 'test', function(done) {
  return gulp.src( './test/*.spec.js', { read: false } )
    .pipe( mocha({
      reporter: 'spec',
      require: ['./test/utils/dom.js'],
      compilers: { js: babel }
    }));
});
```

This works fine, as I change a spec file, the tests get ran (The app is written in ES6).

Now I'm working on a new project and we decided to get Webpack a try, but I'm really struggling to get tests to work.

If I use the above code, then it fails in the line where one of my modules requires a html file (webpack-dev-server handles that with a loader, so in browser, it works fine):

```
import form from '../html/form.html';
```

Of course the issue is that babel itself doesn't know how to handled required html file, which brings me to the question: how can I get Webpack to help me run tests **inside the terminal alone** (with fake dom/jsdom), which means Karma is out of the question as it needs a browser.

Help?

**Comment by cloverich** [comment]
In case anyone ends up here, just wanted to leave this: http://alexfedoseev.com/post/68/test-webpack-specific-builds-with-mocha -- attempts to create a custom compiler for mocha (similar to how you might tell mocah to use `babel-register`).   

Alternatively, I'm investigating having webpack simply generate a test-bundle and feeding that to Mocha to execute with jsdom.
