### ISSUE TITLE
This no longer works with the most recent version of mocha-phantomjs.

### ISSUE THREAD

**Issue by TannerRogalsky** [webpack/mocha-loader#24]
Some breaking changes were introduced in `mocha-phantomjs@4.0`. https://github.com/nathanboktae/mocha-phantomjs/releases/tag/v4.0.0

Result: `mocha was not initialized before the page finished loading. Make sure to include mocha.js as a direct script and call 'mocha.ui' or 'mocha.setup'.`

I modified `start.js` to remove the reference to `mochaPhantomJS` but it did not solve the issue. Reverting to `mocha-phantomjs@3.6.0` resolves the issue.

**Comment by shakefu** [comment]
+1

**Comment by dtuite** [comment]
I just opened a PR which fixes this issue: https://github.com/webpack/mocha-loader/pull/27

**Comment by JanKanty** [comment]
I'm closing the issue due PR fixing it is merged.

**Comment by TannerRogalsky** [comment]
Yep, perfect! Thanks, @JanKanty.
