### ISSUE TITLE
failed tests show up twice

### ISSUE THREAD

**Issue by forresto** [webpack/mocha-loader#28]
[My setup](https://github.com/the-grid/ed/commit/58debdeb5484783979a7b16dee436dd65f18af47) makes failed tests show up twice in the browser runner. It's a pretty simple setup, I'm not sure what could cause the duplication.

Running `mocha` in node doesn't have the issue.

**Comment by ecozoic** [comment]
I'm also noticing duplicate entries for failed tests in the browser.

**Comment by markerikson** [comment]
Yup, same here.  Not immediately sure why that might be happening.  I don't suppose there's any relation to https://github.com/karma-runner/karma-mocha/issues/16 ?

**Comment by AviVahl** [comment]
Root cause: mochajs/mocha#2083
Being worked on at PR: mochajs/mocha#2112

**Comment by markerikson** [comment]
Great, thanks for the update!

**Comment by wirmar** [comment]
The lastest Version of mochajs (v2.5.3) fixes this issue. <https://github.com/mochajs/mocha/pull/2112>

**Comment by JanKanty** [comment]
I'm supposing the problem is solved ;)
