### ISSUE TITLE
maintenance, etc

### ISSUE THREAD

**Issue by boneskull** [webpack/mocha-loader#32]
Hi,

I saw your "call for maintainers" [here](https://medium.com/webpack/webpack-its-getting-real-92c60fca1db1).

Our project may be interested in maintaining this ourselves, but I don't really understand what this module even does or why it's even a thing.

Excuse my ignorance, as I'm not very experienced w/ Webpack.

**Comment by tricoder42** [comment]
Hello 👋 
This loader aims to take advantage of webpack dependency resolution and hot module replacement when running tests using mocha. Ideally, you want to re-run all affected tests every time when you change the code. Thanks to webpack, you can track all dependencies from the file you've just edited and trigger affected tests only.

**Comment by tricoder42** [comment]
@boneskull I'm closing this issue for now. If you're still interested, feel free to submit some PRs or contact us directly. Thank you for your support!
