### ISSUE TITLE
Release a new version supporting v3.0.0 of mocha

### ISSUE THREAD

**Issue by AviVahl** [webpack/mocha-loader#44]
Hello webpack team,

v3.0.0 of mocha was released almost a month ago, which includes some important fixes for us users.
Can we please get a new mocha-loader release that supports it? master is already updated and ready.

We could use the git as source for installing the package, but rather stick to the official package released to npm.

Thanks in advance,

Avi Vahl

**Comment by flyingeagle42** [comment]
japp, npm install mocha-loader does not work, because of the old ^2.0.1 mocha peerDependency. Please update the npm repo with master

**Comment by FlorentD** [comment]
+1

**Comment by tricoder42** [comment]
[v1.0.0](https://github.com/webpack/mocha-loader/releases/tag/v1.0.0) has just been released and published to repo. Thank you for your patience!

**Comment by FlorentD** [comment]
Thank YOU ! ;-)

**Comment by AviVahl** [comment]
Your work is much appreciated. Thank you!
