### ISSUE TITLE
Does Mocha Loader use Mocha 2 rather than Mocha 3 as a peer dependency?

### ISSUE THREAD

**Issue by seanseany** [webpack/mocha-loader#45]
I've installed Mocha 3.0.2, but every time I run node it is complaining:
```mocha-loader@0.7.1 requires a peer of mocha@^2.0.1 but none was installed.```

**Comment by tricoder42** [comment]
Hi, could you try to update `mocha-loader` package first? This has been resolved in https://github.com/webpack/mocha-loader/issues/44
