### ISSUE TITLE
Bundle build fails using webpack 2 dev-server

### ISSUE THREAD

**Issue by lethiandev** [webpack/mocha-loader#47]
New webpack 2 api requires `-loader` suffix on loaders. I ran into this problem using webpack-dev-server as in-browser unit tests. The fix is simple, just edit a file `web.js` in root of the mocha-loader module as below

```javascript
require("!style-loader!css-loader!mocha/mocha.css");
require("!script-loader!mocha/mocha.js");
```

I left it here as an issue, because i'm not sure if it's compatible with stable version of webpack.

**Comment by ahoereth** [comment]
Until merged, the problem can be bypassed by adding the following to your webpack config:

    resolveLoader: {
      moduleExtensions: ['-loader'],
    },
